/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.oodj_assignment;

import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class RegisterAcc extends javax.swing.JFrame {

    /**
     * Creates new form RegisterAcc
     */
    String user;
    String role;
    String uName;
    public RegisterAcc() {
        initComponents();
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowOpened(WindowEvent e) {
                LBLCurrentDate.setText(LocalDate.now().toString());
                User o = new User();
                LBLnewID.setText(String.valueOf(o.getNewID()));
            }
        });
    }
    
    public RegisterAcc(String id, String usr, String rl) {
        initComponents();
        user = id;
        uName = usr;
        role = rl;
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowOpened(WindowEvent e) {
                LBLCurrentDate.setText(LocalDate.now().toString());
                LBLuser.setText("User : "+uName+" ("+role+")");
                User o = new User();
                LBLnewID.setText(String.valueOf(o.getNewID()));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TFpass = new javax.swing.JTextField();
        CBrole = new javax.swing.JComboBox<>();
        TFapW = new javax.swing.JTextField();
        LBLnewID = new javax.swing.JLabel();
        BTNregister = new javax.swing.JButton();
        BTNclear = new javax.swing.JButton();
        LBLCurrentDate = new javax.swing.JLabel();
        BTNback = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TFuName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TFtel = new javax.swing.JTextField();
        LBLuser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TFpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFpassKeyPressed(evt);
            }
        });

        CBrole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer", "Manager" }));
        CBrole.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBroleItemStateChanged(evt);
            }
        });
        CBrole.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CBroleKeyPressed(evt);
            }
        });

        TFapW.setText("0");
        TFapW.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFapWKeyPressed(evt);
            }
        });

        LBLnewID.setText("0");

        BTNregister.setText("Register");
        BTNregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNregisterActionPerformed(evt);
            }
        });

        BTNclear.setText("Clear");
        BTNclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNclearActionPerformed(evt);
            }
        });

        LBLCurrentDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LBLCurrentDate.setText("yyyy-mm-dd");

        BTNback.setText("Back");
        BTNback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNbackActionPerformed(evt);
            }
        });

        jLabel1.setText("Auto-Generated ID :");

        jLabel2.setText("Password :");

        jLabel3.setText("Role :");

        jLabel4.setText("AP-Wallet :");

        jLabel6.setFont(new java.awt.Font("Lucida Sans Unicode", 3, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Register Account");

        jLabel5.setText("Username :");

        TFuName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFuNameKeyPressed(evt);
            }
        });

        jLabel7.setText("Contact :");

        TFtel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFtelKeyPressed(evt);
            }
        });

        LBLuser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBLuser.setText("User : null (null)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LBLnewID, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TFpass, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CBrole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TFapW, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TFuName, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TFtel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(BTNclear)
                        .addGap(30, 30, 30)
                        .addComponent(BTNregister))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(BTNback)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(LBLuser, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LBLCurrentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLuser)
                    .addComponent(LBLCurrentDate))
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(LBLnewID))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(TFpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(CBrole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(TFapW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5))
                    .addComponent(TFuName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7))
                    .addComponent(TFtel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNclear)
                    .addComponent(BTNregister))
                .addGap(8, 8, 8)
                .addComponent(BTNback))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void clear(){
        TFpass.setText("");
        CBrole.setSelectedIndex(0);
        TFapW.setText("0");
        TFuName.setText("");
        TFtel.setText("");
    }
    
    void reload(){
        clear();
        User o = new User();
        LBLnewID.setText(String.valueOf(o.getNewID()));
    }
    
    void resAcc(){
        User o = new User(user);
        o.registerUser(LBLnewID.getText(), TFpass.getText(), CBrole.getSelectedItem().toString(), TFapW.getText(), TFuName.getText(), TFtel.getText());
        reload();
    }
    
    void register(){
        if ("".equals(TFpass.getText())||"".equals(TFuName.getText())||"".equals(TFtel.getText())) {
            JOptionPane.showMessageDialog(null,"Please fill in the details.","Alert",JOptionPane.WARNING_MESSAGE);
        }
        else{
            boolean valid=true;
            if (CBrole.getSelectedIndex()==0) {
                try {
                    float apWallet = Float.parseFloat(TFapW.getText());
                    if (apWallet<0) {
                        JOptionPane.showMessageDialog(null,"Invalid AP-Wallet amount(less than 0).","Alert",JOptionPane.WARNING_MESSAGE);
                        valid=false;
                    }
                    else{
                        TFapW.setText(String.format("%.2f",apWallet));
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null,"Invalid AP-Wallet format.","Alert",JOptionPane.WARNING_MESSAGE);
                    valid=false;
                }
            }
            try {
                Integer.parseInt(TFtel.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null,"Invalid Contact format.","Alert",JOptionPane.WARNING_MESSAGE);
                valid=false;
            }
            if (valid==true) {
                resAcc();
            }
        }
    }
    
    private void BTNclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNclearActionPerformed
        clear();
    }//GEN-LAST:event_BTNclearActionPerformed

    private void BTNbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNbackActionPerformed
        this.setVisible(false);
        new StaffMenu(user,uName,role).setVisible(true);
    }//GEN-LAST:event_BTNbackActionPerformed

    private void CBroleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBroleItemStateChanged
        if (CBrole.getSelectedIndex()==0) {
            TFapW.setEditable(true);
            TFapW.setText("0");
        }
        if (CBrole.getSelectedIndex()==1){
            TFapW.setEditable(false);
            TFapW.setText("-");
        }
    }//GEN-LAST:event_CBroleItemStateChanged
    
    private void BTNregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNregisterActionPerformed
        register();
    }//GEN-LAST:event_BTNregisterActionPerformed

    private void TFpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFpassKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            register();
        }
    }//GEN-LAST:event_TFpassKeyPressed

    private void CBroleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CBroleKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            register();
        }
    }//GEN-LAST:event_CBroleKeyPressed

    private void TFapWKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFapWKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            register();
        }
    }//GEN-LAST:event_TFapWKeyPressed

    private void TFuNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFuNameKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            register();
        }
    }//GEN-LAST:event_TFuNameKeyPressed

    private void TFtelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFtelKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            register();
        }
    }//GEN-LAST:event_TFtelKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterAcc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNback;
    private javax.swing.JButton BTNclear;
    private javax.swing.JButton BTNregister;
    private javax.swing.JComboBox<String> CBrole;
    private javax.swing.JLabel LBLCurrentDate;
    private javax.swing.JLabel LBLnewID;
    private javax.swing.JLabel LBLuser;
    private javax.swing.JTextField TFapW;
    private javax.swing.JTextField TFpass;
    private javax.swing.JTextField TFtel;
    private javax.swing.JTextField TFuName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
