/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.oodj_assignment;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class StaffMenu extends javax.swing.JFrame {

    /**
     * Creates new form StaffMenu
     */
    String user;
    String role;
    String uName;
    public StaffMenu() {
        initComponents();
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowOpened(WindowEvent e) {
                LBLCurrentDate.setText(LocalDate.now().toString());
            }
        });
    }
    
    public StaffMenu(String id, String usr, String rl) {
        initComponents();
        user = id;
        uName = usr;
        role = rl;
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowOpened(WindowEvent e) {
                LBLCurrentDate.setText(LocalDate.now().toString());
                LBLuser.setText("User : "+uName+" ("+role+")");
            }
        });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBLCurrentDate = new javax.swing.JLabel();
        LBLuser = new javax.swing.JLabel();
        BTNregister = new javax.swing.JButton();
        BTNeditMenu = new javax.swing.JButton();
        BTNusersInfo = new javax.swing.JButton();
        BTNlog = new javax.swing.JButton();
        BTNprofUp = new javax.swing.JButton();
        BTNcheckO = new javax.swing.JButton();
        BTNlogout = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        BTNreport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LBLCurrentDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LBLCurrentDate.setText("yyyy-mm-dd");

        LBLuser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBLuser.setText("User : null (null)");

        BTNregister.setText("Register Account");
        BTNregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNregisterActionPerformed(evt);
            }
        });

        BTNeditMenu.setText("Edit Menu");
        BTNeditMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNeditMenuActionPerformed(evt);
            }
        });

        BTNusersInfo.setText("Users Info");
        BTNusersInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNusersInfoActionPerformed(evt);
            }
        });

        BTNlog.setText("Log Record");
        BTNlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNlogActionPerformed(evt);
            }
        });

        BTNprofUp.setText("Profile Update");
        BTNprofUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNprofUpActionPerformed(evt);
            }
        });

        BTNcheckO.setText("Check Orders");
        BTNcheckO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNcheckOActionPerformed(evt);
            }
        });

        BTNlogout.setText("Logout");
        BTNlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNlogoutActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Sans Unicode", 3, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Manager Menu");

        BTNreport.setText("Report");
        BTNreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNreportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(LBLuser, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(LBLCurrentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(BTNeditMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(BTNusersInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(BTNlog, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(BTNcheckO, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(BTNreport, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(BTNlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BTNregister, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNprofUp, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBLuser)
                    .addComponent(LBLCurrentDate))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(BTNprofUp)
                .addGap(12, 12, 12)
                .addComponent(BTNregister)
                .addGap(12, 12, 12)
                .addComponent(BTNeditMenu)
                .addGap(12, 12, 12)
                .addComponent(BTNusersInfo)
                .addGap(12, 12, 12)
                .addComponent(BTNlog)
                .addGap(12, 12, 12)
                .addComponent(BTNcheckO)
                .addGap(12, 12, 12)
                .addComponent(BTNreport)
                .addGap(12, 12, 12)
                .addComponent(BTNlogout)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNregisterActionPerformed
        this.setVisible(false);
        new RegisterAcc(user,uName,role).setVisible(true);
    }//GEN-LAST:event_BTNregisterActionPerformed

    private void BTNlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNlogoutActionPerformed
        User o = new User();
        o.logRecord(user, "out");
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_BTNlogoutActionPerformed

    private void BTNeditMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNeditMenuActionPerformed
        this.setVisible(false);
        new EditMenu(user,uName,role).setVisible(true);
    }//GEN-LAST:event_BTNeditMenuActionPerformed

    private void BTNusersInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNusersInfoActionPerformed
        this.setVisible(false);
        new UsersInfo(user,uName,role).setVisible(true);
    }//GEN-LAST:event_BTNusersInfoActionPerformed

    private void BTNlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNlogActionPerformed
        this.setVisible(false);
        new LogRecord(user,uName,role).setVisible(true);
    }//GEN-LAST:event_BTNlogActionPerformed

    private void BTNprofUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNprofUpActionPerformed
        if ("root".equals(user)) {
            JOptionPane.showMessageDialog(null,"Root account got no profile.","Alert",JOptionPane.WARNING_MESSAGE);
        }
        else{
            this.setVisible(false);
            new UpdateProfile(user,uName,role).setVisible(true);
        }
    }//GEN-LAST:event_BTNprofUpActionPerformed

    private void BTNreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNreportActionPerformed
        this.setVisible(false);
        new Report(user,uName,role).setVisible(true);
    }//GEN-LAST:event_BTNreportActionPerformed

    private void BTNcheckOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNcheckOActionPerformed
        this.setVisible(false);
        new CheckOrders(user,uName,role).setVisible(true);
    }//GEN-LAST:event_BTNcheckOActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNcheckO;
    private javax.swing.JButton BTNeditMenu;
    private javax.swing.JButton BTNlog;
    private javax.swing.JButton BTNlogout;
    private javax.swing.JButton BTNprofUp;
    private javax.swing.JButton BTNregister;
    private javax.swing.JButton BTNreport;
    private javax.swing.JButton BTNusersInfo;
    private javax.swing.JLabel LBLCurrentDate;
    private javax.swing.JLabel LBLuser;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
